blank_issues_enabled: false
contact_links:
  - name: Questions or Feedback
    url: https://github.com/rawatpranjal/metrics-packages/discussions
    about: For general questions, use GitHub Discussions
